//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payment_Karamnov
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Karamnov_DB_PaymentEntities : DbContext
    {
        private static Karamnov_DB_PaymentEntities _context;
        public Karamnov_DB_PaymentEntities()
            : base("name=Karamnov_DB_PaymentEntities")
        {
        }
        public static Karamnov_DB_PaymentEntities GetContext()
        {
            if (_context == null)
                _context = new Karamnov_DB_PaymentEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
